name: Node.js CI

permissions:
  id-token: write  # Нужно для получения JWT токена

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v3
        with:
          yc-sa-id: ajep6pdp79imlp76gidn
          folder-id: b1gbmkj63hnlfu8877sn
          function-name: foobar
          runtime: 'nodejs18'
          memory: 256MB
          entrypoint: 'dist/index.handler'
          service-account: ajep6pdp79imlp76gidn
          source-root: ./fucntions
